name: Create Issue Branch
on:
    issues:
        types: [assigned]

permissions:
  contents: write   # create the branch
  issues: write     # comment on the issue

jobs:
    create_issue_branch:
        runs-on: ubuntu-latest
        steps:
            - name: Create Issue Branch
              uses: robvanderleek/create-issue-branch@main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}